#SPDX-License-Identifier: MIT-0
---
# handlers file for linux_server_hardening
---
- name: Restart SSH
  ansible.builtin.service:
    name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
    state: restarted
